// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.1
//   protoc               v6.33.2
// source: proto/audit.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "audit";

export interface AuditRequest {
  auditId: string;
  message: string;
}

export interface AuditResponse {
  auditId: string;
  message: string;
  extractedNumber: number;
}

export const AUDIT_PACKAGE_NAME = "audit";

export interface AuditServiceClient {
  addAudit(request: AuditRequest): Observable<AuditResponse>;
}

export interface AuditServiceController {
  addAudit(request: AuditRequest): Promise<AuditResponse> | Observable<AuditResponse> | AuditResponse;
}

export function AuditServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["addAudit"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("AuditService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("AuditService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const AUDIT_SERVICE_NAME = "AuditService";
